### PR TITLE
MySQL compatible

### PR DESCRIPTION
**Pull request by trasherdk**
test for db provider - bump version

### CODE REVIEW

**Comment by joshnuss** [comment]
Looks great! Thanks @trasherdk

Maybe one thing to add before merging, wanna add a default condition to the switch statement and throw an error "$provider is not supported yet. Please open a PR"

**Comment by joshnuss** [comment]
Thanks for updating,

Have you tested it with tables that have foreign keys? I think we might have to disable foreign key checks to make it work

**Comment by trasherdk** [comment]
Well.. I don't have a table with foreign key constraint :smile: 

It could look like:
```sql
SET FOREIGN_KEY_CHECKS=0; 
TRUNCATE TABLE tablename; 
SET FOREIGN_KEY_CHECKS=1; 
```

Wrapping the `await Promise.all(commands)` 
```js
if (client.db.provider === 'mysql') await client.$executeRawUnsafe('SET FOREIGN_KEY_CHECKS=0')
await Promise.all(commands)
if (client.db.provider === 'mysql') await client.$executeRawUnsafe('SET FOREIGN_KEY_CHECKS=1')
```

Looks nasty, but how about that?

Edit: Missing a `l` in `mysql`

**Comment by joshnuss** [comment]
Yes, I think that would solve it :)

And it can probably be done with one `Promise.all()`, eg:

```javascript
await Promise.all([
  client.$executeRawUnsafe('SET FOREIGN_KEY_CHECKS=0'),
  ...commands,
  client.$executeRawUnsafe('SET FOREIGN_KEY_CHECKS=1'),
])
```

**Comment by trasherdk** [comment]
Being promises, you have no guaranties of execution order, right?

**Comment by joshnuss** [comment]
Good point! you're initial implementation is correct then, thanks for clarifying

**Comment by joshnuss** [comment]
Thanks @trasherdk 🙌🏻

**Pull request merged**
